### ISSUE TITLE
dataclasses is >= Python 3.7 need to update requirements.txt to support 3.6

### ISSUE THREAD

**Issue by dlazesz** [DavidNemeskey/emBERT#5]
As [line 6 in embert/data_classes.py](https://github.com/DavidNemeskey/emBERT/blob/master/#L6) imports `dataclasses` which requires Python 3.7 minimum the line `dataclasses` needed to be added to requirements.txt for Pyhton 3.6 support.

Please update requirements.txt or correct the supported Python versions in setup.py!

Thank you!

**Comment by DavidNemeskey** [comment]
Fixed in #6.
